### PR TITLE
AutoHotKey client

### PR DESCRIPTION
**Pull request by flagstone78**
I updated it so it handles server errors better. It also includes the license for the Webserver.ahk portion. #137

### CODE REVIEW

**Comment by debsahu** [comment]
@flagstone78 I tried this and works as described. The only annoying (not trying to be mean here) thing in Windows 10 is that the "Tray Message" is on for 3 seconds or so for every key press. Again this is on the windows 10 side, that keeps the message on display for that long. The websocket calls are instantaneous, no lag there. Could we comment out the `TrayTip` lines or is there an `#define ENABLE_XYZ` or a flag that user can set to enable/disable `TrayTip`?

**Comment by debsahu** [comment]
@flagstone78 Do you think you can modify 
```
traytipflag := false ;
.
.
.
if(traytipflag = "true")
		TrayTip, , ....
```

**Comment by flagstone78** [comment]
Ok, the notifications now have their own box.

**Comment by toblum** [comment]
Hi @flagstone78,

thank you for your contribution. I just merged your PR.

Best regards
Tobias

**Pull request merged**
