### PR TITLE
Added MQTT portions to talk to Home Assistant

### PR DESCRIPTION
**Pull request by debsahu**

### CODE REVIEW

**Comment by toblum** [comment]
Hi @debsahu,

thank you for your contribution. I will have a look at it a soon as I find time.

Regards
Tobias

**Comment by debsahu** [comment]
A new update uses ArduinoJSON to hande MQTT requests and messages.

**Comment by toblum** [comment]
Hi @debsahu,

thank you for your contribution. I added the code as a separate branch (https://github.com/toblum/McLighting/tree/feature/ha_integration) and made it configurable via define.
I have no experience with homeassistant because I'm using node red here. And I didn't make it work in a short try. So I don't really know how HASS is working internally.
I'm not so happy with hardcoding all effect names in the code, because currently this wasn't needed as you can get the full list from the WS2812FX library and every change in WS2812FX is reflected automatically. Wouldn't it be possible to use this list also from HASS? Or at least hardcode it only in HASS and not again in the code?

Regards
Tobias

**Comment by debsahu** [comment]
Unfortunately home assistant can only pass effects as strings. So either the user is stuck with using 'LarsonScanner' or '/43'. If they use the later, they don't know what the effect name is and vice versa. Maybe someone more knowledgeable than me could contribute, I'm just a tinkerer.

**Comment by debsahu** [comment]
Yes absolutely, HASS can pass 'FX_MODE_LARSON_SCANNER' etc. Is it simple to convert to effect number if 'FX_MODE_LARSON_SCANNER' is passed?

**Comment by debsahu** [comment]
I mean the message passed is a string 'FX_MODE_LARSON_SCANNER' that needs converting to mode 43.

**Comment by debsahu** [comment]
@toblum I was able to cycle through all modes and search of the incoming mode name passed via HASS. Now hass passes the exact mode name from WS2812FX https://github.com/kitesurfer1404/WS2812FX/blob/b4a153a5a333c2b8edaa20896814432722910752/WS2812FX.h#L223 . Cleans up the code.

**Comment by toblum** [comment]
Hi @debsahu,

thnak you for your contribution. This is what I had in mind. I will have a deeper look at it soon.

Regards
Tobias

**Comment by toblum** [comment]
Hi @debsahu,

this is exactly what I mean. I merged your latest changes into th branch https://github.com/toblum/McLighting/tree/feature/ha_integration. I will have to try that out as soon as I have HASS running.

Maybe someone else could give it also a try.

Regards
Tobias

**Comment by TechOnlyGamer** [comment]
hey guys was waiting for the mqtt json part as soon as i saw mc lightning project. it is working jsut fine for me now... all effects are available via hass for me. color change no problem( dont know where to cinfigure the input slider in ha xD) only which i had would be a nicer way to change the parameters used for the mqtt settings(topic, state) and maybe the unique device id for mqtt to homeassistant as the original sensorname of the esp itself?

**Comment by debsahu** [comment]
@toblum Is it merged yet? It might take some time to update.

@TechOnlyGamer Use my yaml file ( https://github.com/toblum/McLighting/blob/feature/ha_integration/clients/HomeAssistant/light.yaml ). In HA input_slider has been changed to input_number now. In my example "input_number.neopixel_animation_speed" should show up in HA that can be used to manipulate the speed.

**Comment by toblum** [comment]
Hi @debsahu,

yes it should be merged. I also gave you access to the repository if you want to make changes directly there.

Regards
Tobias

**Comment by Yannik25** [comment]
Hallo, thanks for the hard work.
But I can't get it to work
My Home-assistant Config looks like this:
`- platform: mqtt_json
  name: "Decken_LEDs"
  state_topic: "home/DeckenLED/state/out"
  command_topic: "home/DeckenLED/state/in"
  effect: true
  effect_list:
    - Blink
    - Breath
    - Rainbow
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0
  retain: true
`

In definition I changed the Hostname:

const char HOSTNAME[] = "DeckenLED";   // Friedly hostname

#define ENABLE_OTA    
#define ENABLE_MQTT  
#define ENABLE_HOMEASSISTANT

In the serial monitor I only get the standard MQTT topic message:
Attempting MQTT connection 1 / 4 ...
MQTT connected!
MQTT topic in: DeckenLED/in
MQTT topic out: DeckenLED/out


With Mqtt.fx I can monitor the message send from HA:
home/DeckenLED/state/in
{"state": "ON"}

but nothing happen, and no response or any log in serial monitor

**Comment by debsahu** [comment]
Check ”home/DeckenLED_ha/#” ? Add _ha to hostname for HA mqtt topics.

**Comment by Yannik25** [comment]
Thanks for the tip. Now it is working

Now I have another problem, can you check if you have the same behavior?

1. Changing the Color on the McLighting site doesn't change the state at Home-assitent site
2. For example the Rainbow effect in Home-Assistant cycles throw the stripe with only one pixel lit and only in the color selected before. 
I get these two lines in Serial Monitor:

MQTT: Message arrived [{"effect": "Rainbow", "state": "ON"}]
MQTT: Message arrived [{"state":"ON","color":{"r":0,"g":8,"b":255},"brightness":255,"effect":"DualScan"}]

**Comment by debsahu** [comment]
@Yannik25 Could you open an issue here: https://github.com/debsahu/McLighting ? Addressing your issues,

1. True, right now they are separate modules. Once everything work the way they should, I'll add sendState line to Websockets component.
2. I preserve the previous light color state and if you update the light color on HA you don't have to reselect animation. If you want to start animation in a certain color you can define it too in the function, but that's not what I think everyone wants. Feel free to edit the code. Also update your code as now HA needs to send full effect names and not like the one you have from my previous version.

**Pull request closed without merging**
