### PR TITLE
Speed and Stability updates

### PR DESCRIPTION
**Pull request by debsahu**
If LEDs>100, stalls ESP8266. So bunch of code cleanup and merge with
existing variables used by other sections. Should be more efficient. As
of now on Arduino ESP 2.4.1, WiFi.setSleepMode(WIFI_NONE_SLEEP); is
required for MQTT function. ESP8266 is anyways connected to constant
power supply, so power consumtion is not immidiate concern now.
* HTTP OTA
* Arduino OTA
* Async MQTT
* PubSubClient
* HomeAssistant

### CODE REVIEW

**Comment by toblum** [comment]
Thanks again for your contribution. I will have a look at it soon and merge it into master. Just a bit busy at work at the moment.

**Comment by debsahu** [comment]
Take your time, no hurry. I did some major cleanup, could you test by running for a longer time (over 2 hrs)? For some reason all my ESP8266 drop WiFi connection, I am using a ASUS router RT-AC68U. Maybe move these over to a backup dlink router to figure out WiFi stability. WiFiManager (dev version) is quite unstable after 2.4.1 as well: https://github.com/esp8266/Arduino/issues/4372 and same is true for PubSubClient.

**Comment by toblum** [comment]
Hi @debsahu,

I really like your changes, especially to save the state as JSON. This is something I tried a your ago, but it wouldn't work back then. If it works reliably, we could kick the EEPROM code completely.

I was able to compile the code with only some little issues (had to update to ESP core 2.4.1 and a old version of the ESPTCP client made problems). I flashed it now to my testing lamp (24 LEDs) and it works like a charm.

I will keep it running for some time, to test stability, but it looks good. Unfortunately I don't own really big strips.

But before merging this to master I think I have to update the documentation, because setup is slightly more complex. 

Thank you again for this great contribution!

Regards
Tobias

**Comment by debsahu** [comment]
Just set the num_leds to 300 for testing, you dont have to drive 300 leds! Adafruit library uses a lot of memory for 300 leds, just wanted to make sure I am not the only one with the issues. When the leds are set to any value below 30 I have no issues.

**Comment by toblum** [comment]
Yes, I already did that on a second ESP that has 60 LEDs connected effectively (but 300 set in the definitions.h). Works for some time now without problems.

**Comment by toblum** [comment]
One issue I noticed:
State is saved correctly as JSON after a timeout. Checked via: http://192.168.0.49/stripstate.json
When I reset the ESP I see in serial output:
"Read cfg: {"mode":1,"strip_mode":48,"brightness":200,"red":255,"green":76,"blue":0} Success!"
Which is also correct, but the ESP shows complete red and not what's saved.

Could you reproduce this?

**Comment by debsahu** [comment]
You are right, I don't set them. I just read them, I thought mode will set them correctly. Also for some reason I totally forgot about "speed". I'll update in a few hours.

**Comment by debsahu** [comment]
Update should set state correctly

**Comment by debsahu** [comment]
@toblum If you are on Arduino ESP8266 2.4.1, patch WiFiClient.cpp as per https://github.com/esp8266/Arduino/pull/4516 PubSubClient will eventually lead to memory leak after long periods of time. Async MQTT is immune to this for now!

**Comment by debsahu** [comment]
Updates should handle https://github.com/toblum/McLighting/issues/110 as well

**Comment by The-Holgi** [comment]
Hello,
i‘have a ledstrip with 226 led‘s.
It works with the webinterface, but with mqtt over fhem it works for a few time (1 to 3 hour) and than the connection lost. Over webinterface it still works.
Regards
Holger

**Comment by debsahu** [comment]
Could you try my branch and report back? https://github.com/debsahu/McLighting

There is lot going on during a mqtt callback. Now it's simplified and no strip calls are done

**Comment by The-Holgi** [comment]
Hi debsahu,
Thanks for your work.
ESP is flashed with your branch. The Test runs well since 20 minutes.
I´l report tomorrow.
Regards Holger

**Comment by debsahu** [comment]
Also, if you are on Arduino ESP8266 2.4.1, patch WiFiClient.cpp as per my link above for proper functioning of pubsubclient. Or else there will be memory leaks.

**Comment by debsahu** [comment]
Go ahead, I have it running on my test system with 300 and 16 leds. Running fine so far.

**Comment by debsahu** [comment]
@The-Holgi this is off topic, but edit libraries/ESP8266WiFi/src/WiFiClient.cpp (In windows it is in C:\Users\\<USERNAME\>\AppData\appdata\local\Arduino15\packages\esp8266\hardware\esp8266)

replace line 115 `( if (_client) )` with
```
 if (_client) { 
         stop(); 
        _client->unref(); 
        _client = nullptr; 
    }
``` 

Or use latest git version.

**Comment by The-Holgi** [comment]
Hi,
thank you for the tip.
You‘r version (https://github.com/debsahu/McLighting) runs for more than 24 hours without any problems on my wemos d1 mini with 226 led.
Regards Holger

**Pull request closed without merging**
