### PR TITLE
new version hanging

### PR DESCRIPTION
**Pull request by The-Holgi**

### CODE REVIEW

**Comment by debsahu** [comment]
Firstly you are referring to my branch? If so what did you change in definition.h that is causing hang ups. The more details you give, it would be helpful in reproducing your results.

On the issue of merging with master branch, only after @toblum is satisfied with my changes it will be merged. There is a lot of troubleshooting involved. I'll close the other merge request and keep this open.

**Comment by toblum** [comment]
Hi @The-Holgi,
@debsahu branch is working at my desk like a charm, but I didn't find time to merge it into master and to resolve the conflicts. Documentation also needs to be updated. 
You should give this version a try if you not already have used it.

**Comment by The-Holgi** [comment]
Hi, i use the version from your branch debsahu.
In definition.h i only change the num of led“s to 226, the pin for neopixel to pin 5 and the hostname.
The modes like fire, rainbow and other stop the animation after few seconds. Over amqtt it can be restart. Now the device switch from any mode to off by itself.
I reflash the esp and test it again.

**Comment by debsahu** [comment]
I'm tested those animations on my 300 led ws2812b from my branch, no issues on my end. Granted I used NeoAnimationFX(uses pin GPIO3/RX), when I'm back from work later tonight I'll test with latest version of WS2812FX.

**Comment by PhynixP** [comment]
Hello debsahu,
Can you give me a link to the neoanimationfx lib ?

**Comment by debsahu** [comment]
@The-Holgi I modified the speed function to be non-linear (exponential) function. Try changing the speed, from what I expect those animations require an optimum value for speed to show up. It may look like there is nothing going on, but the speed might be too slow. If you want the linear function back comment out line 56 and uncomment line 55 of "request_handlers.h". 

///////// May not be related to what you asked, just putting a note here ////////////
One thing I noticed in WS2812FX is that 1st color is the color you set, 2nd color is usually black and 3rd color for animations that require a third color (like tricolor chase) is also black! I set the third color in NeoAnimationFX as red.

**Comment by The-Holgi** [comment]
Hello,
with a new Wemos D1 mini it runs without any problems.
Maybe the old one has malfunction.
Thanks for your help.

**Comment by toblum** [comment]
@debsahu 
Today I found time to test everything again and merge the code to master. I also updated the Wiki and the notes in the readme.
So I think I catched up with all your changes and I hope I merged everything correctly. If you want you can get the latest version too and see if everything is OK.
Thank again for all your work and sorry for taking so much time to put it into master.

**Pull request merged**
