### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by geyseran**
I would like to test the mesh networking with neo pixels

### CODE REVIEW

**Comment by toblum** [comment]
Hi @geyseran,
the experimental branch can't be merged to master, because this would break the project for all. Why don't you just checkout the experimental branch and test with that?

Regards

**Comment by geyseran** [comment]
Hi Tobias,

 

I cannot download the project as a zip file? See screenshot:

 



 

Regards,

Andre

**Comment by toblum** [comment]
I can't see the screenshot. Just use this link: https://github.com/toblum/McLighting/archive/experimental.zip

**Comment by geyseran** [comment]
Hi Tobias,

 

Thank you for the link. I tried to compile the server sketch with ArduinoJson by Benoit Blanchon library version 5.13.1 and version 6.11.5. I get a number of errors. See attached error log files for both library versions? What would be causing the compile errors?

 

My board settings are the same as in your experimental pictures?

 

Regards,

Andre

**Comment by geyseran** [comment]
Hi Tobias,

 

Would it be possible for you to assist with upgrading the McLighting-experimental project to ArduinoJson 6? I keep on getting the following errors when I try to compile any of the sketches:

 

Arduino: 1.8.9 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (1M SPIFFS), v2 Higher Bandwidth, Disabled, None, Only Sketch, 115200"

 

In file included from C:\Users\Home\Documents\Arduino\McLighting-experimental\McLighting-experimental\Arduino\McLighting\McLighting.ino:218:0:

 

request_handlers.h:692:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

 

       DynamicJsonBuffer jsonBuffer(bufferSize);

 

           ^

request_handlers.h:730:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

 

       DynamicJsonBuffer jsonBuffer(bufferSize);

 

           ^

request_handlers.h:1285:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

 

     DynamicJsonBuffer jsonBuffer(JSON_OBJECT_SIZE(4));

 

           ^

request_handlers.h:1322:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

 

       DynamicJsonBuffer jsonBuffer(JSON_OBJECT_SIZE(4)+300);

 

           ^

request_handlers.h:1354:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

 

   DynamicJsonBuffer jsonBuffer(JSON_OBJECT_SIZE(7));

 

           ^

request_handlers.h:1397:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

 

       DynamicJsonBuffer jsonBuffer(JSON_OBJECT_SIZE(7)+200);

 

           ^

exit status 1

DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

 

 

Regards,

Andre

**Comment by toblum** [comment]
Hi @geyseran,

I don't think that I find time for this at the moment, sorry!

Regards
Tobias

**Pull request closed without merging**
